image: firstdraft/appdev-rails-7-1-template

tasks:
  - before: |
      sudo cp -r /home/student /home/gitpod
      (cd /home/gitpod/student; sudo find . -maxdepth 1 -exec mv {} .. \;)
      source ~/.bashrc
      sudo chmod 777 /home/gitpod && sudo chown -R gitpod /home/gitpod /home/student
      export GEM_HOME=/workspace/.rvm
      export GEM_PATH=$GEM_HOME:$GEM_PATH
      export PATH=/workspace/.rvm/bin:$PATH
      export PGUSER=gitpod
      export POSTGRES_PASSWORD=''
      sudo service postgresql start
      sudo -u postgres psql -c "ALTER USER gitpod WITH PASSWORD '';"
      sudo -u postgres psql -c "CREATE DATABASE cinematch_development;" || true
      sudo -u postgres psql -c "CREATE DATABASE cinematch_test;" || true
      bin/setup
ports:
  - port: 3000
    onOpen: open-preview
    visibility: public
  - port: 4567
    onOpen: open-preview
    visibility: public
  - port: 9292
    onOpen: open-preview
    visibility: public
  - port: 5432
    onOpen: ignore

vscode:
  extensions:
    - vortizhe.simple-ruby-erb
    - mbessey.vscode-rufo
    - aliariff.vscode-erb-beautify
    - eamodio.gitlens
    - setobiralo.erb-commenter
