# Render configuration for Cinematch application
# This file defines both the main app and fetcher service

services:
  # Main Rails application (MRI Ruby)
  - type: web
    name: Cinematch
    runtime: ruby
    plan: starter
    buildCommand: ./bin/render-build.sh
    startCommand: ./bin/render-start.sh
    envVars:
      - key: RAILS_ENV
        value: production
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: cinematch-redis
          property: connectionString
      - key: FETCHER_SERVICE_URL
        value: https://cinematch-fetcher.onrender.com
      - key: CLAMAV_ENABLED
        value: false
    healthCheckPath: /ping
    autoDeploy: true
    buildFilter:
      paths:
      - "**/*.rb"
      - "**/*.erb"
      - "Gemfile*"
      - "config/**/*"
      - "bin/**/*"
    
  # Fetcher service for memory-intensive background jobs
  - type: web
    name: cinematch-fetcher
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile.fetcher
    envVars:
      - key: RAILS_ENV
        value: production
      - key: SECRET_KEY_BASE
        fromService:
          name: Cinematch
          type: web
          envVarKey: SECRET_KEY_BASE
      - key: DATABASE_URL
        fromDatabase:
          name: db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: cinematch-redis
          property: connectionString
      - key: MEMORY_THRESHOLD_MB
        value: 350
      - key: MAX_BATCH_SIZE
        value: 50
      - key: BATCH_SIZE
        value: 20
      - key: MIN_BATCH_SIZE
        value: 3
      - key: PROCESSING_BATCH_SIZE
        value: 5
    healthCheckPath: /fetcher/ping
    autoDeploy: true
    
  # Redis service (Key Value in Render terminology)
  - type: keyvalue
    name: cinematch-redis
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere

# Database - using the existing db
databases:
  - name: db
    ipAllowList: []
