services:
  - type: web
    name: Cinematch 
    env: ruby 
    plan: starter
    buildCommand: "./bin/render-build.sh" 
    startCommand: "./bin/render-start.sh"
    envVars: 
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: db
          property: connectionString
      - key: CLAMAV_ENABLED
        value: true
databases: 
  - name: db
    plan: starter
    ipAllowList: []
